# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsofinterest',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='streets',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
